<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="JuridicalPersonDetails.aspx.cs" Inherits="LegalPersonsProject.JuridicalPersonDetails" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <%-- Contacts --%>
    <asp:ObjectDataSource
        runat="server"
        ID="ContactsObjectDataSource"
        TypeName="LegalPersonsProject.Models.JuridicalPersonRepository"
        SelectMethod="GetContactsById" 
        InsertMethod="InsertContact"
        UpdateMethod="UpdateContact"
        DeleteMethod="DeleteContact">
        <SelectParameters>
            <asp:QueryStringParameter Name="id" QueryStringField="id" />
        </SelectParameters>
        <InsertParameters>
            <asp:QueryStringParameter Name="juridicalPersonId" QueryStringField="id" DbType="Guid" />
            <asp:Parameter Name="physicalPersonId" DbType="Guid" />
            <asp:Parameter Name="position" Type="String" />
        </InsertParameters>
        <DeleteParameters>
            <asp:QueryStringParameter Name="juridicalPersonId" QueryStringField="id" DbType="Guid" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:QueryStringParameter Name="juridicalPersonId" QueryStringField="id" />
            <asp:Parameter Name="physicalPersonId" DbType="Guid" />
            <asp:Parameter Name="position" Type="String" />
        </UpdateParameters>
    </asp:ObjectDataSource>
    <%-- Details --%>
    <asp:ObjectDataSource
        ID="JuridicalPersonDetailsObjectDataSource"
        runat="server"
        TypeName="LegalPersonsProject.Models.JuridicalPersonRepository"
        OldValuesParameterFormatString="{0}"
        SelectMethod="GetById"
        InsertMethod="InsertJuridicalPerson"
        UpdateMethod="UpdateJuridicalPerson"
        DeleteMethod="DeleteJuridicalPerson">
        <SelectParameters>
            <asp:QueryStringParameter Name="id" QueryStringField="id" />
        </SelectParameters>
    </asp:ObjectDataSource>
    <%-- PhysicalPersons --%>
    <asp:ObjectDataSource
        ID="PhysicalPersonsObjectDataSource"
        runat="server"
        TypeName="LegalPersonsProject.Models.PhysicalPersonRepository"
        SelectMethod="GetAll" SortParameterName="SortColumns" EnablePaging="true">
    </asp:ObjectDataSource>
    <asp:DetailsView
        ID="JuridicalPersonDetailsView"
        runat="server"
        DataSourceID="JuridicalPersonDetailsObjectDataSource"
        AutoGenerateRows="false"
        ConflictDetection="CompareAllValues"
        DataKeyNames="Id"
        Gridlines="Both"
        AutoGenerateInsertButton="true"
        AutoGenerateEditButton="true"
        AutoGenerateDeleteButton="true" OnDataBound="JuridicalPersonDetailsView_DataBound"
        OnItemInserted="JuridicalPersonDetailsView_ItemInserted"
        OnItemUpdated="JuridicalPersonDetailsView_ItemUpdated"
        OnItemDeleted="JuridicalPersonDetailsView_ItemDeleted">
        <HeaderStyle BackColor="Navy" ForeColor="White" />
        <RowStyle BackColor="White" />
        <AlternatingRowStyle BackColor="LightGray" />
        <EditRowStyle backcolor="LightCyan" />
        <Fields>
            <asp:BoundField DataField="Id" Visible="false" />
            <asp:BoundField DataField="Name" HeaderText="Название" />
            <asp:BoundField DataField="BINorIIN" HeaderText="БИН" />
            <asp:BoundField DataField="CreatedAt" HeaderText="Дата создания" InsertVisible="false" />          
            <asp:BoundField DataField="UpdatedAt" HeaderText="Дата изменения" InsertVisible="false" />                 
            <asp:BoundField DataField="CreatedBy" HeaderText="Автор" />          
            <asp:BoundField DataField="UpdatedBy" HeaderText="Автор изменения" InsertVisible="false" />
        </Fields>
        
    </asp:DetailsView>
    
    <asp:GridView runat="server" ID="ContactsGridView"
        DataSourceID="ContactsObjectDataSource" DataKeyNames="PhysicalPersonId" AutoGenerateColumns="false"
        AutoGenerateDeleteButton="true" AutoGenerateEditButton="true">
        <Columns>
            <asp:BoundField DataField="PhysicalPersonId" Visible="false"  />
            <asp:BoundField DataField="Name" ReadOnly="true" />
            <asp:BoundField DataField="Secondname" ReadOnly="true" />
            <asp:BoundField DataField="Lastname" ReadOnly="true" />
            <asp:BoundField DataField="BINorIIN" ReadOnly="true" />
            <asp:BoundField DataField="CreatedAt" ReadOnly="true" />
            <asp:BoundField DataField="UpdatedAt" ReadOnly="true" />
            <asp:BoundField DataField="CreatedBy" ReadOnly="true" />
            <asp:BoundField DataField="UpdatedBy" ReadOnly="true" />
            <asp:BoundField DataField="Position" />
        </Columns>
    </asp:GridView>

    <asp:Button runat="server" ID="CreateContactButton" Text="Создать контакт" OnClick="CreateContactButton_Click"   />
    <asp:Label ID="ChooseContactLabel" runat="server" Text="Выберите контакт: " Visible="false"></asp:Label>
    <asp:DropDownList runat="server" ID="PhysicalPersonsDropDownList" Visible="false"
    DataSourceID="PhysicalPersonsObjectDataSource"
    OnSelectedIndexChanged="PhysicalPersonsDropDownList_SelectedIndexChanged" 
    DataTextField="BINorIIN" DataValueField="Id"></asp:DropDownList>
    <asp:Label runat="server" ID="PositionLabel" Visible="false"></asp:Label>
    <asp:TextBox runat="server" ID="PositionTextBox" Visible="false"></asp:TextBox> 
    <asp:Button runat="server" ID="InsertContactButton" Text="Создать" OnClick="InsertContactButton_Click" Visible="false"/>    
</asp:Content>
