<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="PhysicalPersonDetails.aspx.cs" Inherits="LegalPersonsProject.PhysicalPersonDetails" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:ObjectDataSource
        ID="PhysicalPersonDetailsObjectDataSource"
        runat="server"
        TypeName="LegalPersonsProject.Models.PhysicalPersonRepository"
        OldValuesParameterFormatString="{0}"
        SelectMethod="GetById"
        InsertMethod="InsertPhysicalPerson"
        UpdateMethod="UpdatePhysicalPerson"
        DeleteMethod="DeletePhysicalPerson">
        <SelectParameters>
            <asp:QueryStringParameter Name="id" QueryStringField="id" />
        </SelectParameters>
    </asp:ObjectDataSource>

    <asp:DetailsView
        ID="PhysicalPersonDetailsView"
        runat="server"
        DataSourceID="PhysicalPersonDetailsObjectDataSource"
        AutoGenerateRows="false"
        EmptyDataText="Нет записей."
        ConflictDetection="CompareAllValues"
        DataKeyNames="id"
        Gridlines="Both"
        AutoGenerateInsertButton="true"
        AutoGenerateEditButton="true"
        AutoGenerateDeleteButton="true"
        OnItemInserted="PhysicalPersonDetailsView_ItemInserted"
        OnItemUpdated="PhysicalPersonDetailsView_ItemUpdated"
        OnItemDeleted="PhysicalPersonDetailsView_ItemDeleted">
        <HeaderStyle BackColor="Navy" ForeColor="White" />
        <RowStyle BackColor="White" />
        <AlternatingRowStyle BackColor="LightGray" />
        <EditRowStyle backcolor="LightCyan" />
        <Fields>
            <asp:BoundField DataField="Name" HeaderText="Имя" />
            <asp:BoundField DataField="Secondname" HeaderText="Отчество"/>
            <asp:BoundField DataField="Lastname" HeaderText="Фамилия"/>
            <asp:BoundField DataField="BINorIIN" HeaderText="ИИН"/>
            <asp:BoundField DataField="CreatedAt" HeaderText="Дата создания"  InsertVisible="false"/>
            <asp:BoundField DataField="UpdatedAt" HeaderText="Дата изменения" InsertVisible="false"/>
            <asp:BoundField DataField="CreatedBy" HeaderText="Автор"/>
            <asp:BoundField DataField="UpdatedBy" HeaderText="Автор изменения" InsertVisible="false"/>
        </Fields>
       
    </asp:DetailsView>
</asp:Content>
